name: fitness_progress_trackers
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  bloc: ^8.1.4
  cloud_firestore: ^5.4.3
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_core: ^3.5.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_form_builder: ^9.3.0
  form_builder_validators: ^11.0.0
  get_it: ^8.0.2
  intl: ^0.19.0
  logger: ^2.5.0
  shimmer: ^3.0.0
  firebase_auth: ^5.3.4 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^1.0.4
flutter:
  uses-material-design: true

  assets:
    - assets/images/error.jpg
    - assets/images/oops_empty.png

