// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN6CvWsUMwnrdc7rmjJ5UKjq3BKN6uSH8',
    appId: '1:56500026995:web:1d3f1f8ca07731e7623406',
    messagingSenderId: '56500026995',
    projectId: 'fitnesstrackprogress',
    authDomain: 'fitnesstrackprogress.firebaseapp.com',
    storageBucket: 'fitnesstrackprogress.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5AFs2xyMvgfRS0tYu931N73vwuRRe8Y0',
    appId: '1:56500026995:android:3d79cf3a1dc87eac623406',
    messagingSenderId: '56500026995',
    projectId: 'fitnesstrackprogress',
    storageBucket: 'fitnesstrackprogress.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqBV2tFXBZ4pOr5WRl9t6GAmIGQjmt1QQ',
    appId: '1:56500026995:ios:fba9f507ea3d7d64623406',
    messagingSenderId: '56500026995',
    projectId: 'fitnesstrackprogress',
    storageBucket: 'fitnesstrackprogress.firebasestorage.app',
    iosBundleId: 'com.example.fitnessProgressTrackers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqBV2tFXBZ4pOr5WRl9t6GAmIGQjmt1QQ',
    appId: '1:56500026995:ios:fba9f507ea3d7d64623406',
    messagingSenderId: '56500026995',
    projectId: 'fitnesstrackprogress',
    storageBucket: 'fitnesstrackprogress.firebasestorage.app',
    iosBundleId: 'com.example.fitnessProgressTrackers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN6CvWsUMwnrdc7rmjJ5UKjq3BKN6uSH8',
    appId: '1:56500026995:web:59d5731f0bb0626a623406',
    messagingSenderId: '56500026995',
    projectId: 'fitnesstrackprogress',
    authDomain: 'fitnesstrackprogress.firebaseapp.com',
    storageBucket: 'fitnesstrackprogress.firebasestorage.app',
  );

}